name = input("inter a name: ")
game = input("inter a game:  ")  
gmae2 = input("inter game in frist game you write: ")
print("ahmed is a "+name)
print("ahmed love "+game)
print("ahmed play "+gmae2)